/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.event.KeyEvent;
import java.sql.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author siva
 */
public class Subjects extends javax.swing.JFrame {

    /**
     * Creates new form Subjects
     */
    public Subjects() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        locbox = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsubname = new javax.swing.JTextField();
        txtsubcode = new javax.swing.JTextField();
        btn_addsub = new javax.swing.JButton();
        btneditsubject = new javax.swing.JButton();
        btndeletesubject = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmb_yr = new javax.swing.JComboBox<>();
        spinner_lec = new javax.swing.JSpinner();
        spinner_tute = new javax.swing.JSpinner();
        spinner_lab = new javax.swing.JSpinner();
        spinner_eval = new javax.swing.JSpinner();
        rd_seme1 = new javax.swing.JRadioButton();
        rd_seme2 = new javax.swing.JRadioButton();
        clear_subject = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(89, 39, 74));
        jPanel2.setPreferredSize(new java.awt.Dimension(1040, 991));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        locbox.setBackground(new java.awt.Color(255, 255, 255));
        locbox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 39, 74), 3, true));
        locbox.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Offered Year");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Offered Semester");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Subject Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Subject Code");

        txtsubname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubnameActionPerformed(evt);
            }
        });

        txtsubcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubcodeActionPerformed(evt);
            }
        });
        txtsubcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsubcodeKeyPressed(evt);
            }
        });

        btn_addsub.setBackground(new java.awt.Color(0, 51, 0));
        btn_addsub.setForeground(new java.awt.Color(255, 255, 255));
        btn_addsub.setIcon(new javax.swing.ImageIcon("C:\\Users\\siva\\Downloads\\add.png")); // NOI18N
        btn_addsub.setText(" New Subject");
        btn_addsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addsubActionPerformed(evt);
            }
        });

        btneditsubject.setBackground(new java.awt.Color(0, 51, 102));
        btneditsubject.setForeground(new java.awt.Color(255, 255, 255));
        btneditsubject.setIcon(new javax.swing.ImageIcon("C:\\Users\\siva\\Downloads\\edit.png")); // NOI18N
        btneditsubject.setText("Edit");
        btneditsubject.setAlignmentY(0.8F);
        btneditsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditsubjectActionPerformed(evt);
            }
        });

        btndeletesubject.setBackground(new java.awt.Color(153, 0, 51));
        btndeletesubject.setForeground(new java.awt.Color(255, 255, 255));
        btndeletesubject.setIcon(new javax.swing.ImageIcon("C:\\Users\\siva\\Downloads\\delete.png")); // NOI18N
        btndeletesubject.setText("Delete");
        btndeletesubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletesubjectActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(89, 39, 74));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 39, 74), 1, true));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Subjects");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("No of Lecture hours");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("No of Tutorial hours");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("No of Lab hours");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("No of Evaluation hours");

        cmb_yr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4" }));

        spinner_lec.setModel(new javax.swing.SpinnerNumberModel(2, 0, 4, 1));
        spinner_lec.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_lecStateChanged(evt);
            }
        });

        spinner_tute.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        spinner_tute.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_tuteStateChanged(evt);
            }
        });

        spinner_lab.setModel(new javax.swing.SpinnerNumberModel(2, 0, 5, 1));
        spinner_lab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_labStateChanged(evt);
            }
        });

        spinner_eval.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        spinner_eval.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_evalStateChanged(evt);
            }
        });

        rd_seme1.setText("1 st Semester");
        rd_seme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_seme1ActionPerformed(evt);
            }
        });

        rd_seme2.setText("2nd Semester");
        rd_seme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_seme2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout locboxLayout = new javax.swing.GroupLayout(locbox);
        locbox.setLayout(locboxLayout);
        locboxLayout.setHorizontalGroup(
            locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(locboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(locboxLayout.createSequentialGroup()
                        .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rd_seme1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(spinner_eval, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner_lec, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner_lab, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner_tute, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_yr, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtsubname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsubcode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd_seme2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(locboxLayout.createSequentialGroup()
                        .addComponent(btn_addsub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneditsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndeletesubject, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        locboxLayout.setVerticalGroup(
            locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locboxLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_yr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rd_seme1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_seme2)
                .addGap(18, 18, 18)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsubname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubcode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spinner_tute, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinner_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinner_eval, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(locboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addsub)
                    .addComponent(btneditsubject)
                    .addComponent(btndeletesubject))
                .addGap(108, 108, 108))
        );

        clear_subject.setBackground(new java.awt.Color(204, 0, 0));
        clear_subject.setForeground(new java.awt.Color(255, 255, 255));
        clear_subject.setIcon(new javax.swing.ImageIcon("C:\\Users\\siva\\Downloads\\clear.png")); // NOI18N
        clear_subject.setText("Clear history");
        clear_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_subjectActionPerformed(evt);
            }
        });

        jScrollPane3.setForeground(new java.awt.Color(0, 42, 100));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        JTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Offered Year", "Offered Semester", "Subject Name", "Subject Code", "Lecture Hrs", "Tutorial Hrs", "Lab Hrs", "Evaluation Hrs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTable1.setGridColor(new java.awt.Color(89, 39, 74));
        JTable1.setSelectionBackground(new java.awt.Color(89, 39, 74));
        JTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTable1);
        if (JTable1.getColumnModel().getColumnCount() > 0) {
            JTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            JTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
            JTable1.getColumnModel().getColumn(2).setPreferredWidth(110);
            JTable1.getColumnModel().getColumn(3).setPreferredWidth(250);
            JTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
            JTable1.getColumnModel().getColumn(5).setResizable(false);
            JTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            JTable1.getColumnModel().getColumn(6).setPreferredWidth(80);
            JTable1.getColumnModel().getColumn(7).setResizable(false);
            JTable1.getColumnModel().getColumn(7).setPreferredWidth(60);
            JTable1.getColumnModel().getColumn(8).setResizable(false);
            JTable1.getColumnModel().getColumn(8).setPreferredWidth(95);
        }

        jLabel7.setBackground(new java.awt.Color(0, 0, 102));
        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 51));
        jLabel7.setText("MANAGE SUBJECTS");

        jLayeredPane1.setLayer(locbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(clear_subject, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(locbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clear_subject))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(259, 259, 259))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(locbox, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clear_subject)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ABC Institute Timetable Management System");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\siva\\Downloads\\va.jpg")); // NOI18N

        home_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\siva\\Downloads\\home.png")); // NOI18N
        home_btn.setPreferredSize(new java.awt.Dimension(20, 20));
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(home_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(435, 435, 435))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubnameActionPerformed

    private void txtsubcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubcodeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtsubcodeActionPerformed

    private void txtsubcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsubcodeKeyPressed
        

    }//GEN-LAST:event_txtsubcodeKeyPressed

    
        Connection con1;
        PreparedStatement insert;  
        
        private void table_update(){
            
          int c;
          
          try {
            
            Class.forName("com.mysql.jdbc.Driver");
            
            //con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");
            //String url ="jdbc:mysql://timetable-40.mysql.database.azure.com:3306/{university}?useSSL=true&requireSSL=true";
            con1= DriverManager.getConnection("jdbc:mysql://timetable-40.mysql.database.azure.com:3306/university?serverTimezone=UTC", "Janany@timetable-40", "pamathy@25");
          
            insert = con1.prepareStatement("select * From subjects");
            
            ResultSet rs = insert.executeQuery();  
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)JTable1.getModel();
            Df.setRowCount(0);
            
            while(rs.next()) {
                
                Vector v2 = new Vector();
                
                for(int a=1; a<=c; a++) {
                    
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("offered_yr"));
                    v2.add(rs.getString("offered_seme"));
                    v2.add(rs.getString("subject_name"));
                    v2.add(rs.getString("subject_code"));
                    v2.add(rs.getInt("lec_hrs"));
                    v2.add(rs.getInt("tute_hrs"));
                    v2.add(rs.getInt("lab_hrs"));
                    v2.add(rs.getInt("evaluation_hrs"));
                    
                }
                
                Df.addRow(v2);
                  
            }
         
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        }

        
        private boolean Subjects_validateFields(){
        if(cmb_yr.getSelectedItem().toString().equals(" "))
        {
            JOptionPane.showMessageDialog(this,"Select the Year");
            cmb_yr.requestFocus();
            
            return false;
        }
        if( rd_seme1.isSelected()==false && rd_seme2.isSelected()==false )
        {
            JOptionPane.showMessageDialog(this,"Select the Semester");
            rd_seme1.requestFocus();
                
            return false;
        }
 
        if(txtsubname.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter the Subject Name");
            txtsubname.requestFocus();
            
            return false;
        }
        
        if(txtsubcode.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter the Subject Code");
            txtsubcode.requestFocus();
            
            return false;
        }
        
       return true; 
    }
    
    private void btn_addsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addsubActionPerformed
        // TODO add your handling code here:
     
            // Function for radio button action
        
            String OfferedYear = cmb_yr.getSelectedItem().toString();
         
            String OfferedSemester = "";
                if(rd_seme1.isSelected()){
                    OfferedSemester = "Semester 1";
                   }
                if(rd_seme2.isSelected()){
                    OfferedSemester = "Semester 2";
                   }
           
            String SubjectName = txtsubname.getText();
            String SubjectCode = txtsubcode.getText();
            Integer LecHrs = (Integer)spinner_lec.getValue();
            Integer TuteHrs = (Integer)spinner_tute.getValue();
            Integer LabHrs = (Integer)spinner_lab.getValue();
            Integer EvaluationHrs = (Integer)spinner_eval.getValue();
   
            if(Subjects_validateFields()) {
            
        try {
           
            Class.forName("com.mysql.jdbc.Driver");
            
            //con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");
            //String url ="jdbc:mysql://timetable-40.mysql.database.azure.com:3306/{university}?useSSL=true&requireSSL=true";
            con1= DriverManager.getConnection("jdbc:mysql://timetable-40.mysql.database.azure.com:3306/university?serverTimezone=UTC", "Janany@timetable-40", "pamathy@25");
            
            insert = con1.prepareStatement("insert into subjects(offered_yr,offered_seme,subject_name,subject_code,lec_hrs,tute_hrs,lab_hrs,evaluation_hrs)values(?,?,?,?,?,?,?,?)");
            
            insert.setString(1, OfferedYear);
            insert.setString(2, OfferedSemester);
            insert.setString(3, SubjectName); 
            insert.setString(4, SubjectCode);
            insert.setInt(5, LecHrs); 
            insert.setInt(6, TuteHrs);
            insert.setInt(7, LabHrs);
            insert.setInt(8, EvaluationHrs);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"New Subject Added");
            table_update();
          
            
            
            cmb_yr.setSelectedIndex(0); 
            rd_seme1.setSelected(false);
            rd_seme2.setSelected(false);
            txtsubname.setText("");
            txtsubcode.setText("");
            cmb_yr.requestFocus(); 
            
            
        }  catch (ClassNotFoundException ex) {
            Logger.getLogger(Subjects.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Subjects.class.getName()).log(Level.SEVERE, null, ex);
        }
      
     } 

    }//GEN-LAST:event_btn_addsubActionPerformed

    private void btneditsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditsubjectActionPerformed
        // TODO add your handling code here:

        DefaultTableModel Df = (DefaultTableModel)JTable1.getModel();
        int SelectedIndex = JTable1.getSelectedRow();  // to get the data in form when the row is selected
        
        if(SelectedIndex == -1) {
             JOptionPane.showMessageDialog(this,"Select the Subject you want to edit");
         }
        
        else
         
         try {
             
            int id = Integer.parseInt(Df.getValueAt(SelectedIndex, 0).toString());
                     
            String OfferedYear = cmb_yr.getSelectedItem().toString();
            
            String OfferedSemester = "";
                if(rd_seme1.isSelected()){
                    OfferedSemester = "Semester 1";
                   }
                if(rd_seme2.isSelected()){
                    OfferedSemester = "Semester 2";
                   }
                      
            String SubjectName = txtsubname.getText();
            String SubjectCode = txtsubcode.getText();
            Integer LecHrs = (Integer)spinner_lec.getValue();
            Integer TuteHrs = (Integer)spinner_tute.getValue();
            Integer LabHrs = (Integer)spinner_lab.getValue();
            Integer EvaluationHrs = (Integer)spinner_eval.getValue();
          
            int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to update this Subject ?","Warning",JOptionPane.YES_NO_OPTION);
            
            if (dialogResult == JOptionPane.YES_OPTION) {
                         
            Class.forName("com.mysql.jdbc.Driver");
            
            //con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");
            //String url ="jdbc:mysql://timetable-40.mysql.database.azure.com:3306/{university}?useSSL=true&requireSSL=true";
            con1= DriverManager.getConnection("jdbc:mysql://timetable-40.mysql.database.azure.com:3306/university?serverTimezone=UTC", "Janany@timetable-40", "pamathy@25");
          
            insert = con1.prepareStatement("update subjects set offered_yr=?, offered_seme=?, subject_name=?, subject_code=?, lec_hrs=?, tute_hrs=?, lab_hrs=?, evaluation_hrs=? where id=? ");
            
            insert.setString(1, OfferedYear);
            insert.setString(2, OfferedSemester);
            insert.setString(3, SubjectName); 
            insert.setString(4, SubjectCode);
            insert.setInt(5, LecHrs); 
            insert.setInt(6, TuteHrs);
            insert.setInt(7, LabHrs);
            insert.setInt(8, EvaluationHrs);
            insert.setInt(9, id);   
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Subject Updated");
            table_update();
            
            cmb_yr.setSelectedIndex(0); 
            rd_seme1.setSelected(false);
            rd_seme2.setSelected(false);
            txtsubname.setText("");
            txtsubcode.setText("");
            cmb_yr.requestFocus(); 
            
            
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btneditsubjectActionPerformed

    private void btndeletesubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletesubjectActionPerformed
        // TODO add your handling code here:

        DefaultTableModel Df = (DefaultTableModel)JTable1.getModel();
        int SelectedIndex = JTable1.getSelectedRow();  // to get the data in form when the row is selected
        
        if(SelectedIndex == -1) {
             JOptionPane.showMessageDialog(this,"Select the Subject you want to delete");
         }
        
        else
         
         
         try {
             
            int id = Integer.parseInt(Df.getValueAt(SelectedIndex, 0).toString());
            
            int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to delete this Subject ?","Warning",JOptionPane.YES_NO_OPTION);
            
            if (dialogResult == JOptionPane.YES_OPTION) {
                
             Class.forName("com.mysql.jdbc.Driver");
            
            //con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");
            //String url ="jdbc:mysql://timetable-40.mysql.database.azure.com:3306/{university}?useSSL=true&requireSSL=true";
            con1= DriverManager.getConnection("jdbc:mysql://timetable-40.mysql.database.azure.com:3306/university?serverTimezone=UTC", "Janany@timetable-40", "pamathy@25");
          
            insert = con1.prepareStatement("delete from subjects where id=? ");
          
            insert.setInt(1, id);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Subject Deleted");
            table_update();
            
            cmb_yr.setSelectedIndex(0); 
            rd_seme1.setSelected(false);
            rd_seme2.setSelected(false);
            txtsubname.setText("");
            txtsubcode.setText("");
            cmb_yr.requestFocus();    
                    
            }
            
           
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
         

    }//GEN-LAST:event_btndeletesubjectActionPerformed

    private void clear_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_subjectActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel) JTable1.getModel();
          // dtm.setRowCount(0);
        
          
        try {
                      
            int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to clear all the records ?","Warning",JOptionPane.YES_NO_OPTION);
            
            if (dialogResult == JOptionPane.YES_OPTION) {
            
            Class.forName("com.mysql.jdbc.Driver");
            
            //con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");
            //String url ="jdbc:mysql://timetable-40.mysql.database.azure.com:3306/{university}?useSSL=true&requireSSL=true";
            con1= DriverManager.getConnection("jdbc:mysql://timetable-40.mysql.database.azure.com:3306/university?serverTimezone=UTC", "Janany@timetable-40", "pamathy@25");
            
            insert = con1.prepareStatement("Truncate table subjects");
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"All Records got Cleared");
            table_update();
            
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
    }//GEN-LAST:event_clear_subjectActionPerformed

    private void JTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable1MouseClicked
        // TODO add your handling code here
        
        DefaultTableModel Df = (DefaultTableModel)JTable1.getModel();
        int SelectedIndex = JTable1.getSelectedRow();
        
        String OfferedYear = (Df.getValueAt(SelectedIndex, 1).toString());
        switch(OfferedYear){

            case "select":
            cmb_yr.setSelectedIndex(0);
            break;

            case "1":
            cmb_yr.setSelectedIndex(1);
            break;

            case "2":
            cmb_yr.setSelectedIndex(2);
            break;

            case "3":
            cmb_yr.setSelectedIndex(3);
            break;

            case "4":
            cmb_yr.setSelectedIndex(4);
            break;

        }
        
          String OfferedSemester = Df.getValueAt(SelectedIndex, 2).toString();
          
            if(OfferedSemester.equals("Semester 1")){
                rd_seme1.setSelected(true);
                rd_seme2.setSelected(false);
            }
            
            if(OfferedSemester.equals("Semester 2")){
                rd_seme2.setSelected(true);
                rd_seme1.setSelected(false);
            }
       
        
        txtsubname.setText(Df.getValueAt(SelectedIndex, 3).toString());
        txtsubcode.setText(Df.getValueAt(SelectedIndex, 4).toString());
        spinner_lec.setValue((Integer)Df.getValueAt(SelectedIndex, 5));
        spinner_tute.setValue((Integer)Df.getValueAt(SelectedIndex, 6));
        spinner_lab.setValue((Integer)Df.getValueAt(SelectedIndex, 7));
        spinner_eval.setValue((Integer)Df.getValueAt(SelectedIndex, 8));    
       
    }//GEN-LAST:event_JTable1MouseClicked

    private void spinner_lecStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_lecStateChanged
        // TODO add your handling code here:
                   
    }//GEN-LAST:event_spinner_lecStateChanged

    private void spinner_tuteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_tuteStateChanged
        // TODO add your handling code here:
                
    }//GEN-LAST:event_spinner_tuteStateChanged

    private void spinner_labStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_labStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spinner_labStateChanged

    private void spinner_evalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_evalStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spinner_evalStateChanged

    private void rd_seme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_seme2ActionPerformed
        // TODO add your handling code here:
        
        if(rd_seme2.isSelected()){
        rd_seme1.setSelected(false);
        
        }   
    }//GEN-LAST:event_rd_seme2ActionPerformed
   
    private void rd_seme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_seme1ActionPerformed
        // TODO add your handling code here:
        
        if(rd_seme1.isSelected()){
        rd_seme2.setSelected(false);
        
        }
    }//GEN-LAST:event_rd_seme1ActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        
        dashboardnw dbn = new dashboardnw();
        dbn.show();  // display the dashboard
        
        dispose(); //close the current jframe and open the new jframe
        
    }//GEN-LAST:event_home_btnActionPerformed

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable1;
    private javax.swing.JButton btn_addsub;
    private javax.swing.JButton btndeletesubject;
    private javax.swing.JButton btneditsubject;
    private javax.swing.JButton clear_subject;
    private javax.swing.JComboBox<String> cmb_yr;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel locbox;
    private javax.swing.JRadioButton rd_seme1;
    private javax.swing.JRadioButton rd_seme2;
    private javax.swing.JSpinner spinner_eval;
    private javax.swing.JSpinner spinner_lab;
    private javax.swing.JSpinner spinner_lec;
    private javax.swing.JSpinner spinner_tute;
    private javax.swing.JTextField txtsubcode;
    private javax.swing.JTextField txtsubname;
    // End of variables declaration//GEN-END:variables
}
