/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import static java.lang.Integer.parseInt;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mathu
 */
public class WorkingDaysHours extends javax.swing.JFrame {

    /**
     * Creates new form WorkingDaysHours
     */
    public WorkingDaysHours() {
        initComponents();
        table_update();
    }

    
    Connection con1;
        PreparedStatement insert;  
        
        private void table_update(){
            
          int c;
          
          try {
            
            Class.forName("com.mysql.jdbc.Driver");
            
            con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");
          
            insert = con1.prepareStatement("select * From working_days_hours");
            
            ResultSet rs = insert.executeQuery();  
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)workTab.getModel();
            Df.setRowCount(0);
            
            while(rs.next()) {
                
                Vector v2 = new Vector();
                
                for(int a=1; a<=c; a++) {
                    
                    v2.add(rs.getString("TT_ID"));
                    v2.add(rs.getInt("no_working_days"));
                    v2.add(rs.getString("Monday"));
                    v2.add(rs.getString("Tuesday"));
                    v2.add(rs.getString("Wednesday"));
                    v2.add(rs.getString("Thursday"));
                    v2.add(rs.getString("Friday"));
                    v2.add(rs.getString("Saturday"));
                    v2.add(rs.getString("Sunday"));
                    v2.add(rs.getInt("hours_time_per_day"));
                    v2.add(rs.getInt("minutes_time_per_day"));
                    v2.add(rs.getString("time_slot"));
                    
                }
                
                Df.addRow(v2);
                  
            }
         
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        }
          
            
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnoday = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txthours = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txtminutes = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMonday = new javax.swing.JCheckBox();
        txtTuesday = new javax.swing.JCheckBox();
        txtWednesday = new javax.swing.JCheckBox();
        txtThursday = new javax.swing.JCheckBox();
        txtFriday = new javax.swing.JCheckBox();
        txtSaturday = new javax.swing.JCheckBox();
        txtSunday = new javax.swing.JCheckBox();
        one_hour_timeslot = new javax.swing.JRadioButton();
        thirty_minutes_timeslot = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workTab = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(89, 39, 74));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathu\\Downloads\\va.jpg")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ABC Institute Timetable Management System");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathu\\Downloads\\home.png")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("WORKING DAYS HOURS");

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 39, 74), 3));
        form.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("No of Working days");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtnoday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Working Days");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Time per day");

        jLabel7.setText("hours");

        jLabel8.setText("minutes");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Time slot");

        txtMonday.setText("Monday");

        txtTuesday.setText("Tuesday");

        txtWednesday.setText("Wednesday");

        txtThursday.setText("Thursday");

        txtFriday.setText("Friday");

        txtSaturday.setText("Saturday");

        txtSunday.setText("Sunday");

        one_hour_timeslot.setText("1 hour time slot");
        one_hour_timeslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_hour_timeslotActionPerformed(evt);
            }
        });

        thirty_minutes_timeslot.setText("30 minutes time slot");
        thirty_minutes_timeslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirty_minutes_timeslotActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 51, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathu\\Downloads\\add.png")); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 51, 102));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathu\\Downloads\\edit.png")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 0, 51));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathu\\Downloads\\delete.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(89, 39, 74));

        jLabel10.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("WORKING DAYS HOURS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(thirty_minutes_timeslot)
                                            .addComponent(one_hour_timeslot)))
                                    .addGroup(formLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txthours, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(formLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnAdd)
                                .addGap(139, 139, 139)
                                .addComponent(btnDelete)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                                        .addComponent(txtminutes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(formLayout.createSequentialGroup()
                                                .addComponent(txtThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(formLayout.createSequentialGroup()
                                                .addComponent(txtMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(txtTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(formLayout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(btnUpdate))))
                            .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formLayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnoday, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formLayout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnoday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTuesday)
                    .addComponent(txtWednesday)
                    .addComponent(txtMonday))
                .addGap(13, 13, 13)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFriday)
                    .addComponent(txtSaturday)
                    .addComponent(txtThursday))
                .addGap(16, 16, 16)
                .addComponent(txtSunday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtminutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(85, 85, 85)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate)
                            .addComponent(btnAdd))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                        .addComponent(one_hour_timeslot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thirty_minutes_timeslot)
                        .addGap(115, 115, 115))))
        );

        workTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "No of days", "Mon", "Tue", "Wed", "Thurs", "Fri", "Sat", "Sun", "Hours", "Minutes", "Time slot"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        workTab.setSelectionBackground(new java.awt.Color(89, 39, 74));
        workTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(workTab);

        btnClear.setBackground(new java.awt.Color(204, 0, 0));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathu\\Downloads\\clear.png")); // NOI18N
        btnClear.setText("Clear History");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(122, 122, 122)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void thirty_minutes_timeslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirty_minutes_timeslotActionPerformed
        // TODO add your handling code here:
        if(thirty_minutes_timeslot.isSelected()){
            thirty_minutes_timeslot.setSelected(true);
            one_hour_timeslot.setSelected(false);
        }
    }//GEN-LAST:event_thirty_minutes_timeslotActionPerformed

    private void workTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workTabMouseClicked
        // TODO add your handling code here:
        TableModel model = workTab.getModel();
        int j = workTab.getSelectedRow();   // to get the data in form when the row is selected
        
        txtid.setText(model.getValueAt(j, 0).toString());
        
        String no_days = model.getValueAt(j, 1).toString();
        switch(no_days){
            case "1":
                txtnoday.setSelectedIndex(1);
                break;
            case "2":
                txtnoday.setSelectedIndex(2);
                break;
            case "3":
                txtnoday.setSelectedIndex(3);
                break;
            case "4":
                txtnoday.setSelectedIndex(4);
                break;
            case "5":
                txtnoday.setSelectedIndex(5);
                break;
            case "6":
                txtnoday.setSelectedIndex(6);
                break;
            case "7":
                txtnoday.setSelectedIndex(7);
                break;
        }
        
        String Monday = model.getValueAt(j, 2).toString();
        if(Monday.equals("YES")){
            txtMonday.setSelected(true);
        }
        else{
            txtMonday.setSelected(false);
        }
        
        String Tuesday = model.getValueAt(j, 3).toString();
        if(Tuesday.equals("YES")){
            txtTuesday.setSelected(true);
        }
        else{
            txtTuesday.setSelected(false);
        }
        
        String Wednesday = model.getValueAt(j, 4).toString();
        if(Wednesday.equals("YES")){
            txtWednesday.setSelected(true);
        }
        else{
            txtWednesday.setSelected(false);
        }
        
        String Thursday = model.getValueAt(j, 5).toString();
        if(Thursday.equals("YES")){
            txtThursday.setSelected(true);
        }
        else{
            txtThursday.setSelected(false);
        }
        
        String Friday = model.getValueAt(j, 6).toString();
        if(Friday.equals("YES")){
            txtFriday.setSelected(true);
        }
        else{
            txtFriday.setSelected(false);
        }
        
        String Saturday = model.getValueAt(j, 7).toString();
        if(Saturday.equals("YES")){
            txtSaturday.setSelected(true);
        }
        else{
            txtSaturday.setSelected(false);
        }
        
        String Sunday = model.getValueAt(j, 8).toString();
        if(Sunday.equals("YES")){
            txtSunday.setSelected(true);
        }
        else{
            txtSunday.setSelected(false);
        }
        
        txthours.setValue(model.getValueAt(j, 9));
        txtminutes.setValue(model.getValueAt(j, 10));
        
        String timeslot = model.getValueAt(j, 11).toString();
        switch(timeslot){
            case "1 hour time slot":
                one_hour_timeslot.setSelected(true);
                thirty_minutes_timeslot.setSelected(false);
                break;
            case "30 minutes time slot":
                thirty_minutes_timeslot.setSelected(true);
                one_hour_timeslot.setSelected(false);
                break;
        }
    }//GEN-LAST:event_workTabMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String tt_id = txtid.getText();
        String no_days = txtnoday.getSelectedItem().toString();
        Integer days = parseInt(no_days);
        Integer count = 0;
        String Monday = "";
        if(txtMonday.isSelected()){
            Monday = "YES";
            count = count + 1;
        }
        String Tuesday = "";
        if(txtTuesday.isSelected()){
            Tuesday = "YES";
            count = count + 1;
        }
        String Wednesday = "";
        if(txtWednesday.isSelected()){
            Wednesday = "YES";
            count = count + 1;
        }
        String Thursday = "";
        if(txtThursday.isSelected()){
            Thursday = "YES";
            count = count + 1;
        }
        String Friday = "";
        if(txtFriday.isSelected()){
            Friday = "YES";
            count = count + 1;
        }
        String Saturday = "";
        if(txtSaturday.isSelected()){
            Saturday = "YES";
            count = count + 1;
        }
        String Sunday = "";
        if(txtSunday.isSelected()){
            Sunday = "YES";
            count = count + 1;
        }
        Integer hours = (Integer)txthours.getValue();
        Integer minutes = (Integer)txtminutes.getValue();
        String timeslot = "";
        if(one_hour_timeslot.isSelected()){
            timeslot = "1 hour time slot";
        }
        if(thirty_minutes_timeslot.isSelected()){
            timeslot = "30 minutes time slot";
        }
        
        
        if(days == count){
            
        try {
           
            Class.forName("com.mysql.jdbc.Driver");
            
            con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");
            
            insert = con1.prepareStatement("insert into working_days_hours(TT_ID,no_working_days,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,hours_time_per_day,minutes_time_per_day,time_slot)values(?,?,?,?,?,?,?,?,?,?,?,?)");
            
            insert.setString(1, tt_id);
            insert.setInt(2, days);
            insert.setString(3, Monday); 
            insert.setString(4, Tuesday);
            insert.setString(5, Wednesday);
            insert.setString(6, Thursday);
            insert.setString(7, Friday);
            insert.setString(8, Saturday);
            insert.setString(9, Sunday); 
            insert.setInt(10, hours);
            insert.setInt(11, minutes);
            insert.setString(12, timeslot);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"New Timetable format Added");
            table_update();
            
            // To clear the rcords in the form
            txtid.setText("");
            txtnoday.setSelectedIndex(0); 
            txtMonday.setSelected(false);
            txtTuesday.setSelected(false);
            txtWednesday.setSelected(false);
            txtThursday.setSelected(false);
            txtFriday.setSelected(false);
            txtSaturday.setSelected(false);
            txtSunday.setSelected(false);
            txthours.setValue(0);
            txtminutes.setValue(0);
            one_hour_timeslot.setSelected(false);
            thirty_minutes_timeslot.setSelected(false);
            txtid.requestFocus(); 
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(this,"No of Working days are not equal to thecount of selected Working days");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        TableModel model = workTab.getModel();
        
        try {

            int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to clear all the records ?","Warning",JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {

                Class.forName("com.mysql.jdbc.Driver");

                con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");

                insert = con1.prepareStatement("Truncate table working_days_hours");

                insert.executeUpdate();

                JOptionPane.showMessageDialog(this,"All Records got Cleared");
                table_update();

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        TableModel model = workTab.getModel();
        int j = workTab.getSelectedRow();   // to get the data in form when the row is selected
        
        try {

            String tt_id = txtid.getText();
            
            int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to delete this record of Working Days Hours ?","Warning",JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {

                Class.forName("com.mysql.jdbc.Driver");

                con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");

                insert = con1.prepareStatement("delete from working_days_hours where TT_ID=? ");

                insert.setString(1, tt_id);

                insert.executeUpdate();

                JOptionPane.showMessageDialog(this,"record of Working Days Hours is Deleted");
                table_update();

                // To clear the rcords in the form
                txtid.setText("");
                txtnoday.setSelectedIndex(0); 
                txtMonday.setSelected(false);
                txtTuesday.setSelected(false);
                txtWednesday.setSelected(false);
                txtThursday.setSelected(false);
                txtFriday.setSelected(false);
                txtSaturday.setSelected(false);
                txtSunday.setSelected(false);
                txthours.setValue(0);
                txtminutes.setValue(0);
                one_hour_timeslot.setSelected(false);
                thirty_minutes_timeslot.setSelected(false);
                txtid.requestFocus();

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        TableModel model = workTab.getModel();
        int j = workTab.getSelectedRow();   // to get the data in form when the row is selected
        
        try {
           
                String tt_id = txtid.getText();
                String no_days = txtnoday.getSelectedItem().toString();
                Integer days = parseInt(no_days);
                Integer count = 0;
                String Monday = "";
                if(txtMonday.isSelected()){
                    Monday = "YES";
                    count = count + 1;
                }
                String Tuesday = "";
                if(txtTuesday.isSelected()){
                    Tuesday = "YES";
                    count = count + 1;
                }
                String Wednesday = "";
                if(txtWednesday.isSelected()){
                    Wednesday = "YES";
                    count = count + 1;
                }
                String Thursday = "";
                if(txtThursday.isSelected()){
                    Thursday = "YES";
                    count = count + 1;
                }
                String Friday = "";
                if(txtFriday.isSelected()){
                    Friday = "YES";
                    count = count + 1;
                }
                String Saturday = "";
                if(txtSaturday.isSelected()){
                    Saturday = "YES";
                    count = count + 1;
                }
                String Sunday = "";
                if(txtSunday.isSelected()){
                    Sunday = "YES";
                    count = count + 1;
                }
                Integer hours = (Integer)txthours.getValue();
                Integer minutes = (Integer)txtminutes.getValue();
                String timeslot = "";
                if(one_hour_timeslot.isSelected()){
                    timeslot = "1 hour time slot";
                }
                if(thirty_minutes_timeslot.isSelected()){
                    timeslot = "30 minutes time slot";
                }
                
                if(days == count){
        
                int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to update this Employee ?","Warning",JOptionPane.YES_NO_OPTION);

                if (dialogResult == JOptionPane.YES_OPTION) {
                    
                    Class.forName("com.mysql.jdbc.Driver");
            
                    con1= DriverManager.getConnection("jdbc:mysql://localhost/university","root","");
            
                    insert = con1.prepareStatement("update working_days_hours set no_working_days=?, Monday=?, Tuesday=?, Wednesday=?, Thursday=?, Friday=?, Saturday=?, Sunday=?, hours_time_per_day=?, minutes_time_per_day=?, time_slot=? where TT_ID=? ");
            
                        insert.setInt(1, days);
                        insert.setString(2, Monday); 
                        insert.setString(3, Tuesday);
                        insert.setString(4, Wednesday);
                        insert.setString(5, Thursday);
                        insert.setString(6, Friday);
                        insert.setString(7, Saturday);
                        insert.setString(8, Sunday); 
                        insert.setInt(9, hours);
                        insert.setInt(10, minutes);
                        insert.setString(11, timeslot);
                        insert.setString(12, tt_id);
            
                        insert.executeUpdate();
            
                        JOptionPane.showMessageDialog(this,"Timetable format Updated");
                        table_update();
            
                        // To clear the rcords in the form
                        txtid.setText("");
                        txtnoday.setSelectedIndex(0); 
                        txtMonday.setSelected(false);
                        txtTuesday.setSelected(false);
                        txtWednesday.setSelected(false);
                        txtThursday.setSelected(false);
                        txtFriday.setSelected(false);
                        txtSaturday.setSelected(false);
                        txtSunday.setSelected(false);
                        txthours.setValue(0);
                        txtminutes.setValue(0);
                        one_hour_timeslot.setSelected(false);
                        thirty_minutes_timeslot.setSelected(false);
                        txtid.requestFocus(); 
                        
                }
                }
                else{
                    JOptionPane.showMessageDialog(this,"No of Working days are not equal to thecount of selected Working days");
                }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(WorkingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void one_hour_timeslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_hour_timeslotActionPerformed
        // TODO add your handling code here:
        if(one_hour_timeslot.isSelected()){
            one_hour_timeslot.setSelected(true);
            thirty_minutes_timeslot.setSelected(false);
        }
    }//GEN-LAST:event_one_hour_timeslotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkingDaysHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkingDaysHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkingDaysHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkingDaysHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkingDaysHours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel form;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton one_hour_timeslot;
    private javax.swing.JRadioButton thirty_minutes_timeslot;
    private javax.swing.JCheckBox txtFriday;
    private javax.swing.JCheckBox txtMonday;
    private javax.swing.JCheckBox txtSaturday;
    private javax.swing.JCheckBox txtSunday;
    private javax.swing.JCheckBox txtThursday;
    private javax.swing.JCheckBox txtTuesday;
    private javax.swing.JCheckBox txtWednesday;
    private javax.swing.JSpinner txthours;
    private javax.swing.JTextField txtid;
    private javax.swing.JSpinner txtminutes;
    private javax.swing.JComboBox<String> txtnoday;
    private javax.swing.JTable workTab;
    // End of variables declaration//GEN-END:variables
}
